### PR TITLE
Fixed omni, indent with guards and some basic refactoring

### PR DESCRIPTION
**Pull request by kTT**
Please check that my commits reallly fix omni completion and indenting. ;)
There are also some basic refactoring functions as a frontend to wrangler. They can be optionally enabled. I don't know if people will like this.

### CODE REVIEW

**Comment by jimenezrick** [comment]
I merge my repo with kTT changes and all of them seems to me to be a big improvement.

The omni completion works for me now when used twice in the same line.
The guards indenting with `;' also seems fixed.
Very nice feature the highlight of the compiler errors.
I personally don't use wrangler, but it's just one extra file, so I think it's ok to have it in the plugin as an extra feature.

Good job kTT!

**Comment by oscarh** [comment]
I will get to this at some point... hang in there...

**Comment by oscarh** [comment]
I've pulled this in to my kTT branch and will be using this at work for a while. If I don't run in to too much trouble I'll push it to master.

/Oscar

**Comment by jimenezrick** [comment]
OK, if any bug is found, I'll try to look into it.

**Pull request closed without merging**
